### ISSUE TITLE
Permanent settings / remember settings from last time

### ISSUE THREAD

**Issue by linuxlurak** [jhj0517/Whisper-WebUI#250]
It would be nice to have some kind of profiles we could use. an option to save a permanent profile with a drop down box to choos from and perhaps some functionality that remembers the last setup of options. 

Wonderful project, thanks @jhj0517

**Comment by jhj0517** [comment]
The feature for load & cache parameters is applied in #255.

You can update defaults in [default_parameters.yaml](https://github.com/jhj0517/Whisper-WebUI/blob/master/configs/default_parameters.yaml).

If you have any problems with it, please let me know!

**Comment by flier268** [comment]
How do I use that on Docker?
```yaml
services:
    whisper-webui:  
        ports:
            - 7860:7860
        volumes:
          # You can mount the container's volume paths to directory paths on your local machine.
          # Models will be stored in the `./models' directory on your machine.
          # Similarly, all output files will be stored in the `./outputs` directory.
          - ./models:/Whisper-WebUI/models
          - type: bind
            source: ./outputs
            target: /Whisper-WebUI/outputs            
          - type: bind
            source: ./configs
            target: /Whisper-WebUI/configs
```
Previously, the server crashed after upgrading the image.
