### ISSUE TITLE
Timestamps always maximum length when using Silero VAD

### ISSUE THREAD

**Issue by polytr0pe** [jhj0517/Whisper-WebUI#287]
Transcription appears to be accurate, however the ending timestamps for each line are always set at the beginning timestamp of the next line, resulting in subtitles constantly displayed long after speech ends, e.g.:

```
37
00:09:44,419 --> 00:09:56,950
I can't solve the problem at this rate.

38
00:09:56,950 --> 00:10:07,269
What should I do?

39
00:10:07,269 --> 00:10:11,269
I'll take my time and look at it.
``

**Comment by jhj0517** [comment]
Hi, This seems to be default behavior of the whisper, not just VAD.

Regardless of whether each segment tries to start from the end of the previous segment, it should still captrue the correct timestamp.

If the longer segment is the problem, you can try this setting:
```
vad:
  vad_filter: true
  threshold: 0.5
  min_speech_duration_ms: 250
  max_speech_duration_s: 9999
  min_silence_duration_ms: 1000
  speech_pad_ms: 2000
  
bgm_separation:
  is_separate_bgm: false
  model_size: UVR-MDX-NET-Inst_HQ_4
  segment_size: 256
  save_file: false  
```

Turning on the BGM Separation Filter is also helpful in reducing such hallucinations.
