### ISSUE TITLE
Freeing VRAM after timeout

### ISSUE THREAD

**Issue by ei23fxg** [jhj0517/Whisper-WebUI#413]
I'm using this great program as a Docker container and I'm wondering if it would be possible to remove the Whisper model from the VRAM after a certain time so that it doesn't permanently block the VRAM.
Maybe some kind of timeout parameter would be useful, so that you can set it to 60 seconds, for example, and after 60 seconds of standby the model is removed from the VRAM again.

Restarting the container is currently my workaround.

```
  whisper-webui:
    build:
      context: ./volumes/openedai-speech/.
      dockerfile: dockerfile
    image: jhj0517/whisper-webui:latest
    container_name: Whisper-WebUI
    restart: no
    volumes:
      - ./volumes/Whisper-WebUI/models:/Whisper-WebUI/models
      - ./volumes/Whisper-WebUI/outputs:/Whisper-WebUI/outputs
      - ./volumes/Whisper-WebUI/configs:/Whisper-WebUI/configs
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    entrypoint: ["python", "app.py", "--server_port", "7860", "--whisper_type", "insanely-fast-whisper", "--api_open", "True", "--server_name", "0.0.0.0",]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
```
