### ISSUE TITLE
The docker image latest, pushed on Feb 5, 2025 does not work

### ISSUE THREAD

**Issue by janusn** [jhj0517/Whisper-WebUI#497]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.] Alpine Linux 3.21.0 64bit
 - installation: Docker version 27.5.1, build 9f9e405
 - docker image: [latest](https://hubgw.docker.com/layers/jhj0517/whisper-webui/latest/images/sha256-c4605a57535cf1a588dd10ae3dd4f654eb109ec5a9e97fd82cec4073109aa900) pushed on Feb 5, 2025.

**compose.yaml**
```
services:
  app:
    build: .
    image: jhj0517/whisper-webui:latest
    container_name: whisper-webui
    volumes:
      - ./models:/Whisper-WebUI/models
      - ./outputs:/Whisper-WebUI/outputs
      - ./configs:/Whisper-WebUI/configs
      - ./app/requirements.txt:/Whisper-WebUI/requirements.txt
      - type: tmpfs
        target: /tmp
    environment:
      - OMP_NUM_THREADS=24
      - SUBTITLE_LANGUAGE_NAMING_TYPE=ISO_639_3
    ports:
      - 7860:7860
    stdin_open: true
    tty: true
    entrypoint:
      - python
      - app.py
      - --server_port
      - "7860"
      - --server_name
      - 0.0.0.0
      - --username
      - janus
      - --password
      - "6xbwTsd_C3fq"
      - --colab
      - "False"
    deploy:
      resources:
        limits:
          memory: 16G
```
**Issue:**
The webui was running fine. The facebook nllb and whisper was working before pulling image pushed on Feb 5, 2025.

Now, the webpage shows loading... as shown below.

![Image](https://github.com/user-attachments/assets/71afad27-1598-486d-b38e-e8997566c194)

**log:**
```
# docker logs whisper-webui
Use "faster-whisper" implementation
Device "auto" is detected
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```
